#!/usr/bin/env bash
# This Script connects to the server 18.207.235.100 using the users private key
# stored in a file school Found in the users home directory

ssh -i ~/.ssh/school ubuntu@18.207.235.100
